# LED
OLED_ENABLE = yes
OLED_DRIVER = SSD1306

# Encoder
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

# Keys
EXTRAKEY_ENABLE = yes
REPEAT_KEY_ENABLE = yes
DYNAMIC_MACRO_ENABLE = no
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no

# Speaker
AUDIO_ENABLE = yes
MUSIC_ENABLE = yes

# Haptic Feedback
HAPTIC_ENABLE = yes

# RGB
RGB_MATRIX_ENABLE = yes